/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package splash;

/**
 *
 * @author JeianneBMelecio
 */
public class Splashscreen extends javax.swing.JFrame {

    /**
     * Creates new form Splashscreen
     */
    public Splashscreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progress = new javax.swing.JLabel();
        bar = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 360));
        setUndecorated(true);
        getContentPane().setLayout(null);

        progress.setBackground(new java.awt.Color(0, 0, 0));
        progress.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        progress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        progress.setText("0%");
        getContentPane().add(progress);
        progress.setBounds(0, 270, 500, 20);
        getContentPane().add(bar);
        bar.setBounds(50, 304, 390, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Loading....");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 330, 500, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\JeianneBMelecio\\Downloads\\Modern Monogram A Logo (3).png")); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(500, 360));
        jLabel1.setMinimumSize(new java.awt.Dimension(0, 0));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 360);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
      Splashscreen sc = new Splashscreen();
      sc.setVisible(true);
      
 
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                sc.setVisible(true);
            }
        });
        Splash s = new Splash();
        try {
            for(int i = 0;i<=100;i++)
            {
                Thread.sleep(40);
                sc.bar.setValue(i);
                sc.progress.setText(Integer.toString(i)+"%");
                
            }    
        }catch (Exception e){         
        }
        new Splashscreen().setVisible(false);
        sc.setVisible(true);
        sc.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar bar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel progress;
    // End of variables declaration//GEN-END:variables
}
